Feature/azure blob handler
AARK-Global-Inc-Main-Code-Repo/Citadel-IDP-Src pull request #26
Opened 2023-08-21 10:37 UTC by ashishchib2

Updates

2023-08-21 11:43 UTC, saikiranreddy098 commented on src/common/utils.py
>        str:  returns object of class Metadata
put type to be object

2023-08-21 11:46 UTC, saikiranreddy098 commented on src/common/utils.py
>      metadata.content_md5 = base64.b64encode(properties.content_settings.content_md5).decode("utf-8")
check what  if the content_md5 is  None while pulling from azure storage.

2023-08-21 18:17 UTC, Mister-Raggs requested changes

2023-08-21 18:17 UTC, Mister-Raggs commented on README.md
> +1.  Install azurite on your local system.
For a third party, installation steps / link to a guide should be provided.

2023-08-21 18:17 UTC, Mister-Raggs commented on azurite_local_storage/__blobstorage__/865fdfb5-b869-4403-8e28-b691b3966026
2-3 bin files were added, make sure these are necessary to run the program and aren't giving away unnecessary information.

2023-08-21 18:17 UTC, Mister-Raggs commented on scripts/activate_azurite.bat
what is the purpose of removing @echo off?

2023-08-21 18:17 UTC, Mister-Raggs commented on src/services/blob_handler.py
would need some clarification in this section of code

2023-08-22 02:39 UTC, ashishchib2 commented on scripts/activate_azurite.bat
This will show the command that is present in batch file while executing that batch file.

2023-08-22 12:10 UTC, closed without merging

2023-08-22 12:10 UTC, saikiranreddy098 commented
request closed